# Generated by Django 5.0.6 on 2026-06-19 11:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('zone', models.CharField(choices=[('A', 'Zone A - Premium'), ('B', 'Zone B - Standard'), ('C', 'Zone C - Economy')], max_length=2)),
                ('slot_type', models.CharField(choices=[('car', 'Car'), ('bike', 'Bike'), ('ev', 'EV Charging')], max_length=10)),
                ('has_charger', models.BooleanField(default=False)),
                ('status', models.CharField(default='active', max_length=20)),
                ('base_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['floor', 'status'], name='parking_par_floor_d01345_idx'), models.Index(fields=['zone', 'slot_type'], name='parking_par_zone_9f74ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone', models.CharField(blank=True, max_length=2, null=True)),
                ('day_of_week', models.IntegerField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('multiplier', models.DecimalField(decimal_places=1, max_digits=3)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['day_of_week', 'is_active'], name='parking_pri_day_of__1e92cd_idx'), models.Index(fields=['zone'], name='parking_pri_zone_f9d6ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=20)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('reserved', 'Reserved - Not Checked In'), ('active', 'Active - Vehicle Inside'), ('completed', 'Completed - Paid & Left'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue - Penalty Applied')], default='reserved', max_length=20)),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('qr_code', models.TextField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parking.parkingslot')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'status'], name='parking_boo_user_id_9ebdf4_idx'), models.Index(fields=['start_time'], name='parking_boo_start_t_a2f3c4_idx'), models.Index(fields=['slot', 'start_time', 'end_time'], name='parking_boo_slot_id_14f085_idx')],
            },
        ),
    ]
