# Generated by Django 6.0.6 on 2026-06-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='parking_pri_day_of__1e92cd_idx',
        ),
        migrations.RemoveIndex(
            model_name='pricingrule',
            name='parking_pri_zone_f9d6ac_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_user_id_1eeb34_idx',
            old_name='parking_boo_user_id_9ebdf4_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_start_t_3b5408_idx',
            old_name='parking_boo_start_t_a2f3c4_idx',
        ),
        migrations.RenameIndex(
            model_name='booking',
            new_name='bookings_slot_id_1e4747_idx',
            old_name='parking_boo_slot_id_14f085_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingslot',
            new_name='parking_slo_floor_ab56bd_idx',
            old_name='parking_par_floor_d01345_idx',
        ),
        migrations.RenameIndex(
            model_name='parkingslot',
            new_name='parking_slo_zone_de9caa_idx',
            old_name='parking_par_zone_9f74ac_idx',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='reserved', max_length=20),
        ),
        migrations.AlterModelTable(
            name='booking',
            table='bookings',
        ),
        migrations.AlterModelTable(
            name='parkingslot',
            table='parking_slots',
        ),
        migrations.AlterModelTable(
            name='pricingrule',
            table='pricing_rules',
        ),
    ]
