# Generated by Django 6.0.6 on 2026-07-07 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_alter_parkingslot_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=20)),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed')], default='active', max_length=20)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_hours', models.PositiveIntegerField(default=0)),
                ('amount_due', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'parking_sessions',
                'ordering': ['-check_in_time'],
            },
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_user_id_1eeb34_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_start_t_3b5408_idx',
        ),
        migrations.RemoveIndex(
            model_name='booking',
            name='bookings_slot_id_1e4747_idx',
        ),
        migrations.AlterModelOptions(
            name='parkingslot',
            options={'ordering': ['floor', 'slot_number']},
        ),
        migrations.RemoveIndex(
            model_name='parkingslot',
            name='parking_slo_floor_ab56bd_idx',
        ),
        migrations.RemoveIndex(
            model_name='parkingslot',
            name='parking_slo_zone_de9caa_idx',
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='base_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='floor',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='slot_type',
            field=models.CharField(choices=[('car', 'Car'), ('motorbike', 'Motorbike'), ('ev', 'Electric Vehicle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='parkingslot',
            name='zone',
            field=models.CharField(choices=[('A', 'Zone A - Premium'), ('B', 'Zone B - Standard'), ('C', 'Zone C - Economy')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='zone',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='parking.parkingslot'),
        ),
        migrations.AddField(
            model_name='parkingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
