# Generated by Django 6.0.6 on 2026-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0005_rename_amount_due_parkingsession_mpesa_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingsession',
            name='payment_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='active', max_length=20),
        ),
    ]
