# Generated by Django 6.0.6 on 2026-07-07 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('gate_staff', 'Gate Staff'), ('admin', 'Admin')], default='driver', max_length=20),
        ),
    ]
