# Generated by Django 6.0.6 on 2026-07-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='default_vehicle',
            field=models.CharField(blank=True, default='', help_text='Default vehicle registration plate.', max_length=20),
        ),
    ]
