# Generated by Django 6.0.6 on 2026-06-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='booking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
