# Generated by Django 6.0.6 on 2026-07-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0002_mpesatransaction_booking_id'),
        ('parking', '0005_rename_amount_due_parkingsession_mpesa_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='parking_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='parking.parkingsession'),
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='transaction_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
