# Generated by Django 6.0.6 on 2026-07-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0003_remove_mpesatransaction_booking_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mpesatransaction',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='mpesatransaction',
            name='callback_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='mpesa_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterModelTable(
            name='mpesatransaction',
            table='mpesa_transactions',
        ),
    ]
